# Data Binning and Data Formating Using Python
## VEdant mathur
## PRN: - 25070123120

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000,20000,30000,2000,8000,45000],
    'Units_Sold': [25,60,35,80,50,15]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low', 'Medium', 'High']

df['Price_Category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)
df

      Product  Price  Units_Sold Price_Category
3  Headphones   2000          80            Low
1      Mobile  20000          60         Medium
4  Smartwatch   8000          50            Low
2      Tablet  30000          35         Medium
0      Laptop  55000          25           High
5      Camera  45000          15           High

In [ ]:
#Data binnig sold
bins2 = [0,30,60,100]
labels2 = ['Low sales', 'Medium Sales', 'High sales']

df['Sales_Category'] = pd.cut(df['Units_Sold'], bins=bins2, labels=labels2)
df

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low sales

In [ ]:
# data formating
#convert data type

print(df.dtypes)
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)
df

Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low sales

In [ ]:
#convert text to uppercase
df['Product'] = df['Product'].str.upper()
df

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low sales

In [ ]:
# Rounding values
df['Price'] = df['Price'].round(2)

df

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#additional operation
#Sort data

sorted_df = df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
5      CAMERA  45000        15.0           High      Low sales
0      LAPTOP  55000        25.0           High      Low sales

In [ ]:

df.sort_values(by='Units_Sold', inplace = True)
print(df)

      Product  Price  Units_Sold
5      Camera  45000          15
0      Laptop  55000          25
2      Tablet  30000          35
4  Smartwatch   8000          50
1      Mobile  20000          60
3  Headphones   2000          80

In [ ]:
df.sort_values(by=['Units_Sold'], inplace = True, ascending = False)
print(df)

      Product  Price  Units_Sold
3  Headphones   2000          80
1      Mobile  20000          60
4  Smartwatch   8000          50
2      Tablet  30000          35
0      Laptop  55000          25
5      Camera  45000          15

In [ ]:
#Display Unique Values
print(df['Price_Category'].unique())

['Low', 'Medium', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Order_ID': ['01','02','03','04','05','06','07','08'],
    'Order_Value': [250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_Km':[5,8,3,10,6,2,9,4]

}
df = pd.DataFrame(data)
df

  Order_ID  Order_Value  Delivery_Time  Distance_Km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [ ]:
#Binning oder values

bins=[0,200,400,700]
labels = ['Low Order', 'Medium Order', 'High Order']

df['Order_Category'] = pd.cut(df['Order_Value'], bins=bins, labels=labels)
df

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order_Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [ ]:
bins2 = [0,30,45,70]
labels2 = ['Fast Delivery','Normal Delivery','Slow Delivery']
df['Delivery_Category'] = pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
df

,Order_ID,Order_Value,Delivery_Time,Distance_Km,Order_Category,Delivery_Category
0,01,250,30,5,Medium Order,Fast Delivery
1,02,450,45,8,High Order,Normal Delivery
2,03,120,25,3,Low Order,Fast Delivery
3,04,600,60,10,High Order,Slow Delivery
4,05,300,35,6,Medium Order,Normal Delivery
5,06,150,20,2,Low Order,Fast Delivery
6,07,500,50,9,High Order,Slow Delivery
7,08,220,28,4,Medium Order,Fast Delivery

In [ ]:
bins3 = [0,4,8,12]
labels3 = ['far','moderately far','close']
df['Distance_Category'] = pd.cut(df['Distance_Km'],bins=bins3,labels=labels3)
df

,Order_ID,Order_Value,Delivery_Time,Distance_Km,Order_Category,Delivery_Category,Distance_Category
0,01,250,30,5,Medium Order,Fast Delivery,moderately far
1,02,450,45,8,High Order,Normal Delivery,moderately far
2,03,120,25,3,Low Order,Fast Delivery,far
3,04,600,60,10,High Order,Slow Delivery,close
4,05,300,35,6,Medium Order,Normal Delivery,moderately far
5,06,150,20,2,Low Order,Fast Delivery,far
6,07,500,50,9,High Order,Slow Delivery,close
7,08,220,28,4,Medium Order,Fast Delivery,far

In [ ]:
print(df['Order_Category'].value_counts())
df

Order_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_Km,Order_Category,Delivery_Category
0,01,250,30,5,Medium Order,Fast Delivery
1,02,450,45,8,High Order,Normal Delivery
2,03,120,25,3,Low Order,Fast Delivery
3,04,600,60,10,High Order,Slow Delivery
4,05,300,35,6,Medium Order,Normal Delivery
5,06,150,20,2,Low Order,Fast Delivery
6,07,500,50,9,High Order,Slow Delivery
7,08,220,28,4,Medium Order,Fast Delivery